new/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views

# 正在部署的应用的名称
app_name = 'news'

urlpatterns = [
    # path函数将url映射到视图
    path('', views.new_list, name='new_list'),
    # 文章详情
    path('news-detail/<int:id>/', views.news_detail, name='news_detail'),
    url(r'^search/$', views.news_search ),
    # path('search/<str:theme>/', views.news_search, name='news_search'),

    path('daohang/<str:class_name>/', views.news_show, name='news_show'),

    path('daohang/<str:tags>/', views.news_show_tags, name='news_show_tags')
]

news/urls.py
from django.conf.urls.static import static, settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  # 后台
    path('', include('new.urls', namespace='new')),  # 新闻
    path('ckeditor/', include('ckeditor_uploader.urls')),  # 富文本编辑器
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),  # 用户
    path('password-reset/', include('password_reset.urls')),  # 重置密码
    path('comment/', include('comment.urls', namespace='comment')),  # 评论
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户注册
    path('register/', views.user_register, name='register'),

    # 用户退出
    path('logout/', views.user_logout, name='logout'),
]

userprofile/models.py
from django.db import models

# Create your models here.

userprofile/forms.py
# 引入表单类
from django import forms
# 引入 User 模型
from django.contrib.auth.models import User


# 登录表单，继承了 forms.Form 类
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

# 注册用户表单
class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    # 对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from .forms import UserLoginForm
from comment.models import Comment
# 引入 UserRegisterForm 表单类
from .forms import UserLoginForm, UserRegisterForm

from new.models import  news,Tag
# Create your views here.


# 用户登录
def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                
                # 将用户数据保存在 session 中，即实现了登录动作
                login(request, user)

                new = news.objects.all().reverse()[:5]
                tui1 = news.objects.order_by('tui')[0]
                tui2 = news.objects.order_by('tui')[1]
                xuexiao_qian = news.objects.order_by('-created_time').filter(tags__name="学校")[0]
                xuexiao_hou = news.objects.order_by('-created_time').filter(tags__name="学校")[1:4]
                dangwu_qian = news.objects.order_by('-created_time').filter(category__name="党务工作")[0]
                dangwu_hou = news.objects.order_by('-created_time').filter(category__name="党务工作")[1:4]
                xueshu_qian = news.objects.order_by('-created_time').filter(category__name="学术交流")[0]
                xueshu_hou = news.objects.order_by('-created_time').filter(category__name="学术交流")[1:4]
                bisai_qian = news.objects.order_by('-created_time').filter(category__name="各类赛事")[0]
                bisai_hou = news.objects.order_by('-created_time').filter(category__name="各类赛事")[1:4]
                suzhi_qian = news.objects.order_by('-created_time').filter(category__name="素质教育")[0]
                suzhi_hou = news.objects.order_by('-created_time').filter(category__name="素质教育")[1:4]
                qita_qian = news.objects.order_by('-created_time').filter(category__name="其他")[0]
                qita_hou = news.objects.order_by('-created_time').filter(category__name="其他")[1:4]
                redian = news.objects.order_by('-views')[:4]
                zuixin = news.objects.order_by('-created_time')[:4]
                pinglun = Comment.objects.order_by('-created')[:4]
                tuijian = news.objects.order_by('tui')[:4]

                context = {
                'news': new,
                'tui1':tui1,
                'tui2':tui2,
                'xuexiao_qian':xuexiao_qian,
                'xuexiao_hou':xuexiao_hou,
                'dangwu_qian':dangwu_qian,
                'dangwu_hou':dangwu_hou,
                'xueshu_qian':xueshu_qian,
                'xueshu_hou':xueshu_hou,
                'bisai_qian':bisai_qian,
                'bisai_hou':bisai_hou,
                'suzhi_qian':suzhi_qian,
                'suzhi_hou':suzhi_hou,
                'qita_qian':qita_qian,
                'qita_hou':qita_hou,
                'redian' :redian,
                'zuixin' :zuixin,
                'pinglun' :pinglun,
                'tuijian' :tuijian

                }
                return render(request, 'news/index.html', context)
            else:
                return HttpResponse("账号或密码输入有误。请重新输入~")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = { 'form': user_login_form }
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


# 用户注册
def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return render(request, 'userprofile/login.html')
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = { 'form': user_register_form }
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")



# 用户退出
def user_logout(request):
    logout(request)
    new = news.objects.all().reverse()[:5]
    tui1 = news.objects.order_by('tui')[0]
    tui2 = news.objects.order_by('tui')[1]
    xuexiao_qian = news.objects.order_by('-created_time').filter(tags__name="学校")[0]
    xuexiao_hou = news.objects.order_by('-created_time').filter(tags__name="学校")[1:4]
    dangwu_qian = news.objects.order_by('-created_time').filter(category__name="党务工作")[0]
    dangwu_hou = news.objects.order_by('-created_time').filter(category__name="党务工作")[1:4]
    xueshu_qian = news.objects.order_by('-created_time').filter(category__name="学术交流")[0]
    xueshu_hou = news.objects.order_by('-created_time').filter(category__name="学术交流")[1:4]
    bisai_qian = news.objects.order_by('-created_time').filter(category__name="各类赛事")[0]
    bisai_hou = news.objects.order_by('-created_time').filter(category__name="各类赛事")[1:4]
    suzhi_qian = news.objects.order_by('-created_time').filter(category__name="素质教育")[0]
    suzhi_hou = news.objects.order_by('-created_time').filter(category__name="素质教育")[1:4]
    qita_qian = news.objects.order_by('-created_time').filter(category__name="其他")[0]
    qita_hou = news.objects.order_by('-created_time').filter(category__name="其他")[1:4]
    redian = news.objects.order_by('-views')[:4]
    zuixin = news.objects.order_by('-created_time')[:4]
    pinglun = Comment.objects.order_by('-created')[:4]
    tuijian = news.objects.order_by('tui')[:4]

    context = {'news': new,
    'tui1':tui1,
    'tui2':tui2,
    'xuexiao_qian':xuexiao_qian,
    'xuexiao_hou':xuexiao_hou,
    'dangwu_qian':dangwu_qian,
    'dangwu_hou':dangwu_hou,
    'xueshu_qian':xueshu_qian,
    'xueshu_hou':xueshu_hou,
    'bisai_qian':bisai_qian,
    'bisai_hou':bisai_hou,
    'suzhi_qian':suzhi_qian,
    'suzhi_hou':suzhi_hou,
    'qita_qian':qita_qian,
    'qita_hou':qita_hou,
    'redian' :redian,
    'zuixin' :zuixin,
    'pinglun' :pinglun,
    'tuijian' :tuijian

    }

    return render(request, 'news/index.html', context)

templates/userprofile/login.html
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>

            </form>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <br>
            <h5>还没有账号？</h5>
            点击<a href='{% url "userprofile:register" %}'>注册账号</a>加入我们吧！
            <br>
            <form method="post" action=".">

            </form>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>
</div>


{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %} {% load static %}
{% block title %} 注册 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">昵称</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 邮箱 -->
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-4">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}