comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:id>/', views.post_comment, name='post_comment'),

]

new/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views

# 正在部署的应用的名称
app_name = 'news'

urlpatterns = [
    # path函数将url映射到视图
    path('', views.new_list, name='new_list'),
    # 文章详情
    path('news-detail/<int:id>/', views.news_detail, name='news_detail'),
    url(r'^search/$', views.news_search ),
    # path('search/<str:theme>/', views.news_search, name='news_search'),

    path('daohang/<str:class_name>/', views.news_show, name='news_show'),

    path('daohang/<str:tags>/', views.news_show_tags, name='news_show_tags')
]

news/urls.py
from django.conf.urls.static import static, settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  # 后台
    path('', include('new.urls', namespace='new')),  # 新闻
    path('ckeditor/', include('ckeditor_uploader.urls')),  # 富文本编辑器
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),  # 用户
    path('password-reset/', include('password_reset.urls')),  # 重置密码
    path('comment/', include('comment.urls', namespace='comment')),  # 评论
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户注册
    path('register/', views.user_register, name='register'),

    # 用户退出
    path('logout/', views.user_logout, name='logout'),
]

new/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
# Create your models here.


# 新闻分类
class Category(models.Model):
    name = models.CharField(verbose_name='新闻分类', max_length=100)
    index = models.IntegerField(default=1, verbose_name='分类排序')

    class Meta:
        verbose_name = '类别管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 新闻标签
class Tag(models.Model):
    name = models.CharField('新闻标签', max_length=100)

    class Meta:
        verbose_name = '标签管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tui(models.Model):
    name = models.CharField('推荐位', max_length=100)


    class Meta:
        verbose_name = '推荐位'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 新闻
class news(models.Model):
    title = models.CharField('标题', max_length=70)
    excerpt = models.TextField('摘要', max_length=200, blank=True)

    # 使用外键关联分类表与分类是一对多关系
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, verbose_name='分类', blank=True, null=True)
    # 使用外键关联标签表与标签是多对多关系
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)

    img = models.ImageField(upload_to='article_img/%Y/%m/%d/', verbose_name='封面图片', blank=True, null=True)
    content = RichTextUploadingField(verbose_name='正文')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')
    tui = models.ForeignKey(Tui, on_delete=models.DO_NOTHING, verbose_name='推荐位', blank=True, null=True)
    views = models.PositiveIntegerField('阅读量', default=0)
    created_time = models.DateTimeField('发布时间', auto_now_add=True)
    modified_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        verbose_name = '文章详情'
        verbose_name_plural = '文章管理'

    def __str__(self):
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('news:news_detail', args=[self.id])






# 友情链接
class Link(models.Model):
    name = models.CharField('链接名称', max_length=20)
    linkurl = models.URLField('网址', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = '友情链接'

new/views.py
from django.shortcuts import render, HttpResponse
from .models import Tag, news
from django.views.generic import View, ListView
from comment.models import Comment
from numpy import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def new_list(request):
    try:

        new = news.objects.all().reverse()[:5]
        tui1 = news.objects.order_by('tui')[0]
        tui2 = news.objects.order_by('tui')[1]
        xuexiao_qian = news.objects.order_by('-created_time').filter(tags__name="学校")[0]
        xuexiao_hou = news.objects.order_by('-created_time').filter(tags__name="学校")[1:4]
        dangwu_qian = news.objects.order_by('-created_time').filter(category__name="党务工作")[0]
        dangwu_hou = news.objects.order_by('-created_time').filter(category__name="党务工作")[1:4]
        xueshu_qian = news.objects.order_by('-created_time').filter(category__name="学术交流")[0]
        xueshu_hou = news.objects.order_by('-created_time').filter(category__name="学术交流")[1:4]
        bisai_qian = news.objects.order_by('-created_time').filter(category__name="各类赛事")[0]
        bisai_hou = news.objects.order_by('-created_time').filter(category__name="各类赛事")[1:4]
        suzhi_qian = news.objects.order_by('-created_time').filter(category__name="素质教育")[0]
        suzhi_hou = news.objects.order_by('-created_time').filter(category__name="素质教育")[1:4]
        qita_qian = news.objects.order_by('-created_time').filter(category__name="其他")[0]
        qita_hou = news.objects.order_by('-created_time').filter(category__name="其他")[1:4]
        redian = news.objects.order_by('-views')[:4]
        zuixin = news.objects.order_by('-created_time')[:4]
        pinglun = Comment.objects.order_by('-created')[:4]
        tuijian = news.objects.order_by('tui')[:4]

        context = {'news': new,
        'tui1':tui1,'tui2':tui2,
        'xuexiao_qian':xuexiao_qian,
        'xuexiao_hou':xuexiao_hou,
        'dangwu_qian':dangwu_qian,
        'dangwu_hou':dangwu_hou,
        'xueshu_qian':xueshu_qian,
        'xueshu_hou':xueshu_hou,
        'bisai_qian':bisai_qian,
        'bisai_hou':bisai_hou,
        'suzhi_qian':suzhi_qian,
        'suzhi_hou':suzhi_hou,
        'qita_qian':qita_qian,
        'qita_hou':qita_hou,
        'redian' :redian,
        'zuixin' :zuixin,
        'pinglun' :pinglun,
        'tuijian' :tuijian

        }

        # render函数：载入模板，并返回context对象
        return render(request, 'news/index.html', context)

    except:
        return HttpResponse("没有找到数据！!")



def news_detail(request, id):
    new = news.objects.get(id=id)
    # 浏览量 +1
    new.views += 1
    new.save(update_fields=['views'])
    new = news.objects.get(id=id)

    # 取出评论
    comments = Comment.objects.filter(new=id)

    # 需要传递给模板的对象
    context = {'new': new, 'comments': comments, }
    # 载入模板，并返回context对象
    return render(request, 'news/detail.html', context)

def news_search(request):

    data=request.POST['search_text']
    redian = news.objects.order_by('-views')[:4]
    zuixin = news.objects.order_by('-created_time')[:4]
    pinglun = Comment.objects.order_by('-created')[:4]
    tuijian = news.objects.order_by('tui')[:4]
    theme = news.objects.filter(title__contains=data)
    paginator = Paginator(theme, 2) 
     
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:

        contacts = paginator.page(paginator.num_pages)
    

    # context={'redian' :redian,
    #     'zuixin' :zuixin,
    #     'pinglun' :pinglun,
    #     'tuijian' :tuijian,
    #     'contacts' :theme}
    return render(request, 'news/show.html', {'redian' :redian,
        'zuixin' :zuixin,
        'pinglun' :pinglun,
        'tuijian' :tuijian,
        'contacts' :contacts})



def news_show(request, class_name):
    try:
        redian = news.objects.order_by('-views')[:4]
        zuixin = news.objects.order_by('-created_time')[:4]
        pinglun = Comment.objects.order_by('-created')[:4]
        tuijian = news.objects.order_by('tui')[:4]
        class_name = news.objects.filter(category__name=class_name)
        paginator = Paginator(class_name, 2) 
     
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:

            contacts = paginator.page(paginator.num_pages)
    
        return render(request, 'news/show.html', {'redian' :redian,
        'zuixin' :zuixin,
        'pinglun' :pinglun,
        'tuijian' :tuijian,
        'contacts' :contacts})
    except:
        return HttpResponse("news_show没有找到数据！!")


def news_show_tags(request,tags):
    try:
        redian = news.objects.order_by('-views')[:4]
        zuixin = news.objects.order_by('-created_time')[:4]
        pinglun = Comment.objects.order_by('-created')[:4]
        tuijian = news.objects.order_by('tui')[:4]
        class_name = news.objects.filter(tags__name=tags)

        paginator = Paginator(class_name, 2) 

     
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:

            contacts = paginator.page(paginator.num_pages)

        return render(request, 'news/show.html', {'contacts' :contacts,
        'redian' :redian,
        'zuixin' :zuixin,
        'pinglun' :pinglun,
        'tuijian' :tuijian})
    except:
        return HttpResponse("news_show_tags没有找到数据！!")


templates/news/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ new.title }}</h1>
        <div class="col-12 alert alert-success">作者：{{ new.user }} &nbsp;&nbsp;&nbsp;&nbsp; 发布时间：{{ new.created_time }}
            &nbsp;&nbsp;&nbsp;&nbsp; 浏览量：{{ new.views }}
        </div>


        <!-- 文章正文 -->
        <div  >
            <p >{{new.content}}</p>
        </div>
    </div>
</div>



</script>
<!-- 发表评论 -->
<hr>
{% if user.is_authenticated %}
<div class="container">
    <div class="col-24">
        <form
                action="{% url 'comment:post_comment' new.id %}"
                method="POST"
        >
            {% csrf_token %}

            <div class="form-group">
                <label for="content">
                    <h4>
                        我也要发表评论：
                    </h4>
                </label>
                <textarea
                        type="text"
                        class="form-control"
                        id="content"
                        name="content"
                        rows="2"></textarea> </label>
            </div>
            <!-- 提交按钮 -->
            <button type="submit" class="btn btn-primary ">发送</button>
        </form>
    </div>
    <br>
    {% else %}
    <br>
    <h5 class="row justify-content-center">
        请<a href="{% url 'userprofile:login' %}">登录</a>后回复
    </h5>
    <br>
    {% endif %}


    <!-- 显示评论 -->
    <div class="container">
        <div class="row">
            <h4>共有{{ comments.count }}条评论</h4>
        </div>


        {% for comment in comments %}
        <hr>
        <p>
            <strong style="color: pink">
                {{ comment.user }}
            </strong> 于
            <span style="color: green">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> 发表评论：
        <p style="font-family: inherit; font-size: 1em;">
            {{ comment.content }}</p>
        </p>

        {% endfor %}
    </div>
</div>


{% endblock content %}

templates/news/show.html
{% extends "base.html" %} {% load static %}
{% block title %} 新闻网站| 首页 {% endblock title %}
{% block content %}





<!-- 居中布局 -->
<div class="main-container container mt-40" id="main-container">

    <!-- 内容 -->
    <div class="row">

        <!-- Posts -->
        <div class="col-lg-8 blog__content mb-30">
        	{% for new in contacts %}
        		<br>
        		<br>
				<article class="post-list-small__entry clearfix">
                    <div class="post-list-small__img-holder">
                        <div class="thumb-container thumb-75">
                            <a href="{% url 'news:news_detail' new.id %}">
                                <img data-src="/media/{{new.img}}"
                                     src="/media/{{new.img}}" alt="" class=" lazyload">
                            </a>
                        </div>
                    </div>
                    <div class="post-list-small__body">
                        <h3 class="post-list-small__entry-title">
                            <a href="{% url 'news:news_detail' new.id %}">{{new.title}}</a>
                        </h3>
                        <ul class="entry__meta">
                            <li class="entry__meta-date">
                                <i class="ui-date"></i>
                                {{new.modified_time}}
                            </li>
                        </ul>
                    </div>
                </article>
            {% endfor %}
            <br>

			

            <div >
			    <span >
			    	<span >
			        {% if contacts.has_previous %}
			            <a href="?page={{ contacts.previous_page_number }}">&laquo;</a>
			        {% endif %}
			     	</span >
			 		 Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}
			        <span >
			        {% if contacts.has_next %}
			            <a href="?page={{ contacts.next_page_number }}">&raquo;</a>
			        {% endif %}
			        </span>
			    </span>
			</div>


        </div>

        <!-- end posts -->

        <!-- 右边 -->
        <aside class="col-lg-4 sidebar sidebar--right">

            

            <!-- 三格栅 -->
            <div class="widget widget-tabpost">
                <div class="tabs widget-tabpost__tabs">
                    <ul class="tabs__list widget-tabpost__tabs-list">
                        <li class="tabs__item widget-tabpost__tabs-item tabs__item--active">
                            <a href="#tab-trending" class="tabs__url tabs__trigger widget-tabpost__tabs-url">热点</a>
                        </li>
                        <li class="tabs__item widget-tabpost__tabs-item">
                            <a href="#tab-latest"
                               class="tabs__url tabs__trigger widget-tabpost__tabs-url">最新</a>
                        </li>
                        <li class="tabs__item widget-tabpost__tabs-item">
                            <a href="#tab-comments" class="tabs__url tabs__trigger widget-tabpost__tabs-url">评论</a>
                        </li>
                    </ul> <!-- end tabs -->

                    <!-- tab content -->
                    <div class="tabs__content tabs__content-trigger widget-tabpost__tabs-content">

                        <div class="tabs__content-pane tabs__content-pane--active" id="tab-trending">
                            <ul class="post-list-small">
                                {% for new in redian %}
                                <li class="post-list-small__item">
                                    <article class="post-list-small__entry clearfix">
                                        <div class="post-list-small__img-holder">
                                            <div class="thumb-container thumb-75">
                                                <a href="{% url 'news:news_detail' new.id %}">
                                                    <img data-src="/media/{{new.img}}"
                                                         src="/media/{{new.img}}" alt="" class=" lazyload">
                                                </a>
                                            </div>
                                        </div>
                                        <div class="post-list-small__body">
                                            <h3 class="post-list-small__entry-title">
                                                <a href="{% url 'news:news_detail' new.id %}">{{new.title}}</a>
                                            </h3>
                                            <ul class="entry__meta">
                                                <li class="entry__meta-date">
                                                    <i class="ui-date"></i>
                                                    {{new.modified_time}}
                                                </li>
                                            </ul>
                                        </div>
                                    </article>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>

                        <div class="tabs__content-pane" id="tab-latest">
                            <ul class="post-list-small">
                                {% for new in zuixin %}
                                <li class="post-list-small__item">
                                    <article class="post-list-small__entry clearfix">
                                        <div class="post-list-small__img-holder">
                                            <div class="thumb-container thumb-75">
                                                <a href="{% url 'news:news_detail' new.id %}">
                                                    <img data-src="/media/{{new.img}}"
                                                         src="/media/{{new.img}}" alt="" class=" lazyload">
                                                </a>
                                            </div>
                                        </div>
                                        <div class="post-list-small__body">
                                            <h3 class="post-list-small__entry-title">
                                                <a href="{% url 'news:news_detail' new.id %}">{{new.title}}</a>
                                            </h3>
                                            <ul class="entry__meta">
                                                <li class="entry__meta-date">
                                                    <i class="ui-date"></i>
                                                    {{new.modified_time}}
                                                </li>
                                            </ul>
                                        </div>
                                    </article>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>

                        <div class="tabs__content-pane" id="tab-comments">
                            <ul class="post-list-small">
                                {% for new in pinglun %}
                                <li class="post-list-small__item">
                                    <article class="post-list-small__entry clearfix">
                                        <div class="post-list-small__img-holder">
                                            <div class="thumb-container thumb-75">
                                                <a href="{% url 'news:news_detail' new.new.id %}">
                                                    <img data-src="/media/{{new.new.img}}"
                                                         src="/media/{{new.new.img}}" alt="" class=" lazyload">
                                                </a>
                                            </div>
                                        </div>
                                        <div class="post-list-small__body">
                                            <h3 class="post-list-small__entry-title">
                                                <a href="{% url 'news:news_detail' new.new.id %}">{{new.new.title}}</a>
                                            </h3>
                                            <ul class="entry__meta">
                                                <li class="entry__meta-date">
                                                    <i class="ui-date"></i>
                                                    {{new.new.modified_time}}
                                                </li>
                                            </ul>
                                        </div>
                                    </article>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>

                    </div> <!-- end tab content -->
                </div> <!-- end tabs -->
            </div> <!-- end widget popular/latest posts -->



            <!-- 好评 -->
            <div class="widget widget-reviews">
                <h4 class="widget-title">推荐</h4>
                <ul class="post-list-small">
                    {% for new in tuijian%}
                    <li class="post-list-small__item">
                        <article class="post-list-small__entry clearfix">
                            <div class="post-list-small__img-holder">
                                <div class="thumb-container thumb-75">
                                    <a href="{% url 'news:news_detail' new.id %}">
                                        <img data-src="/media/{{new.img}}"
                                             src="/media/{{new.img}}" alt="" class=" lazyload">
                                    </a>
                                </div>
                            </div>
                            <div class="post-list-small__body">
                                <h3 class="post-list-small__entry-title">
                                    <a href="{% url 'news:news_detail' new.id %}">{{new.title}}</a>
                                </h3>
                                <ul class="entry__meta">
                                    <li class="entry__meta-rating">
                                        <i class="ui-star"></i>
                                        <i class="ui-star"></i>
                                        <i class="ui-star"></i>
                                        <i class="ui-star"></i>
                                        <i class="ui-star-outline"></i>
                                    </li>
                                </ul>
                            </div>
                        </article>
                    </li>
                    {% endfor %}
                </ul>
            </div>


            <!-- 加入我们 -->
            <div class="widget">
                <h4 class="widget-title">加入我们</h4>
                <div class="tweets-container">
                    <div id="tweets">
                        <p>QQ交流：*****</p>
                        <p>VX交流：*****</p>
                        <p>邮箱交流：*****@163.com</p>
                        <p>投稿邮箱：*****@qq.com</p>

                    </div>
                </div>
            </div>





        </aside> <!-- end sidebar -->

    </div> <!-- end content -->
</div>
<!-- end main container -->

{% endblock content %}  