new/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views

# 正在部署的应用的名称
app_name = 'news'

urlpatterns = [
    # path函数将url映射到视图
    path('', views.new_list, name='new_list'),
    # 文章详情
    path('news-detail/<int:id>/', views.news_detail, name='news_detail'),
    url(r'^search/$', views.news_search ),
    # path('search/<str:theme>/', views.news_search, name='news_search'),

    path('daohang/<str:class_name>/', views.news_show, name='news_show'),

    path('daohang/<str:tags>/', views.news_show_tags, name='news_show_tags')
]

news/urls.py
from django.conf.urls.static import static, settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  # 后台
    path('', include('new.urls', namespace='new')),  # 新闻
    path('ckeditor/', include('ckeditor_uploader.urls')),  # 富文本编辑器
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),  # 用户
    path('password-reset/', include('password_reset.urls')),  # 重置密码
    path('comment/', include('comment.urls', namespace='comment')),  # 评论
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户注册
    path('register/', views.user_register, name='register'),

    # 用户退出
    path('logout/', views.user_logout, name='logout'),
]

templates/base.html

{% load static %}


<html lang="en">
<head>

<!--     {% block title %}

    {% endblock title %} -->
    <title>
        小灿新闻
    </title>

    <meta charset="utf-8">



    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet'>

    <!-- Css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-icons.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>



    <!-- Lazyload -->
    <script src="{% static 'js/lazysizes.min.js' %}"></script>

</head>


<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
{% block content %}


{% endblock content %}
<!-- 引入注脚 -->
{% include 'footer.html' %}


</main> <!-- end main-wrapper -->

<!-- jQuery Scripts -->



<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/easing.min.js' %}"></script>
<script src="{% static 'js/owl-carousel.min.js' %}"></script>
<script src="{% static 'js/twitterFetcher_min.js' %}"></script>
<script src="{% static 'js/jquery.newsTicker.min.js' %}"></script>
<script src="{% static 'js/modernizr.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>

</body>
</html>

templates/footer.html
<footer class="footer footer--dark">

    <div class="footer__bottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 order-lg-2 text-right text-md-center">
                    <div class="widget widget_nav_menu">
                        <ul>
                            <li><a href="#">条款</a></li>
                            <li><a href="#">隐私</a></li>
                            <li><a href="#">广告</a></li>
                            <li><a href="#">通讯</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-5 order-lg-1 text-md-center">
              <span class="copyright">
                &copy; 2021 联系方式 | ******@163.com <a href="http://www.dedeask.com"></a>
              </span>
                </div>
            </div>

        </div>
    </div> <!-- end bottom footer -->
</footer> <!-- end footer -->

templates/header.html

<body class="bg-light"> 


<!-- Bg Overlay -->
<div class="content-overlay"></div>
<!--左部导航 -->
<header class="sidenav" id="sidenav">

    <!-- close -->
    <div class="sidenav__close">
        <button class="sidenav__close-button" id="sidenav__close-button" aria-label="close sidenav">
            <i class="ui-close sidenav__close-icon"></i>
        </button>
    </div>

    <!-- Nav -->
    <nav class="sidenav__menu-container">
        <ul class="sidenav__menu" role="menubar">
            <!-- Categories -->
            <li>
                <a href="{% url 'news:news_show_tags' '学校' %}" class="sidenav__menu-link sidenav__menu-link-category sidenav__menu-link--orange">学校热点</a>
            </li>
            <li>
                <a href="{% url 'news:news_show' '党务工作' %}" class="sidenav__menu-link sidenav__menu-link-category sidenav__menu-link--blue">党务工作</a>
            </li>
            <li>
                <a href="{% url 'news:news_show' '学术交流' %}" class="sidenav__menu-link sidenav__menu-link-category sidenav__menu-link--red">学术交流</a>
            </li>
            <li>
                <a href="{% url 'news:news_show' '各类赛事' %}" class="sidenav__menu-link sidenav__menu-link-category sidenav__menu-link--salad">各类赛事</a>
            </li>
            <li>
                <a href="{% url 'news:news_show' '素质教育' %}" class="sidenav__menu-link sidenav__menu-link-category sidenav__menu-link--purple">素质教育</a>
            </li>
            <li>
                <a href="{% url 'news:news_show' '其他' %}" class="sidenav__menu-link sidenav__menu-link-category sidenav__menu-link--yellow">其他</a>
            </li>


            <li>
                <a href="#" class="sidenav__menu-link">关于</a>
            </li>

        </ul>
    </nav>

</header> <!-- end sidenav -->

<main class="main oh" id="main">

    <!-- 顶部 -->
    <header class="nav">

        <div class="nav__holder nav--sticky">
            <div class="container relative">
                <div class="flex-parent">

                    <!-- Side Menu Button -->
                    <button class="nav-icon-toggle" id="nav-icon-toggle" aria-label="Open side menu">
              <span class="nav-icon-toggle__box">
                <span class="nav-icon-toggle__inner"></span>
              </span>
                    </button> <!-- end Side menu button -->

                    <!-- Mobile logo -->
                    <a href="index.html" class="logo logo--mobile d-lg-none">
                        <img class="logo__img" src="static/img/logo_mobile.png"
                             srcset="static/img/logo_mobile.png 1x, static/img/logo_mobile@2x.png 2x" alt="logo">
                    </a>

                    <!-- Nav-wrap -->
                    <nav class="flex-child nav__wrap d-none d-lg-block">
                        <ul class="nav__menu">

                            <li class="active">

                                <a href=' http://127.0.0.1:8000/ '>首页</a>

                            </li>
                            <li class="active">

                                <a href="http://127.0.0.1:8000/">HOME</a>

                            </li>


                        </ul> <!-- end menu -->
                    </nav> <!-- end nav-wrap -->

                    <!-- Nav Right -->
                    <div class="nav__right nav--align-right d-lg-flex">
                        <div >
                                <a href="#top" ><i class="ui-arrow-up"></i></a>
                        </div>
                        <!-- Search -->
                        <div class="nav__right-item nav__search">
                            <a href="#" class="nav__search-trigger" id="nav__search-trigger">
                                <i class="ui-search nav__search-trigger-icon"></i>
                            </a>
                            <div class="nav__search-box" id="nav__search-box">
                                <form class="nav__search-form" method="POST" action="/search/">
                                    {% csrf_token %}
                                    <input type="text" placeholder="Search an article" class="nav__search-input" name='search_text' id='search_text'>
                                    <button type="submit" class="search-button btn btn-lg btn-color btn-button">
                                        <i class="ui-search nav__search-icon"></i>
                                    </button>
                                </form>
                            </div>

                        </div>

                    </div> <!-- end nav right -->

                </div> <!-- end flex-parent -->
            </div> <!-- end container -->

        </div>
    </header> <!-- end navigation -->


    <!-- 导航 -->
    <div class="header">
        <div class="container">
            <div class="flex-parent align-items-center">

                <!-- Logo -->
                <a href="http://127.0.0.1:8000/" class="logo d-none d-lg-block" >
                    <h3>小灿新闻网</h3>
                </a>

                <!-- Ad Banner 728 -->
                <div class="text-center">
                    <ul class="row">
                        <!-- 条目 -->


                        <!-- Django的 if 模板语句 -->
                        {% if user.is_authenticated %}
                        <!-- 如果用户已经登录，则显示用户名下拉框 -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" font_size=25>
                                {{ user.username }}&nbsp&nbsp&nbsp&nbsp&nbsp
                            </a>
                        <li class="nav-item">
                            <a class="nav-link" href='{% url "userprofile:logout" %}'>退出登录</a>
                        </li>

                        </li>
                        <!-- 如果用户未登录，则显示 “登录” -->
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                        </li>
                        <!-- if 语句在这里结束 -->
                        {% endif %}


                    </ul>
                </div>


            </div>
        </div>
    </div> <!-- end header -->

    <!-- 滚动 -->
    <div class="trending-now">
        <div class="container relative">
            <span class="trending-now__label">公告</span>
            <ul class="newsticker">
                <li class="newsticker__item"><a class="newsticker__item-url">欢迎来到校园新闻首页</a></li>
                <li class="newsticker__item"><a  class="newsticker__item-url">注册登录后方可评论新闻</a></li>
                <li class="newsticker__item"><a  class="newsticker__item-url">发布新闻请联系后台工作人员</a></li>
            </ul>
            <div class="newsticker-buttons">
                <button class="newsticker-button newsticker-button--prev" id="newsticker-button--prev"
                        aria-label="next article"><i class="ui-arrow-left"></i></button>
                <button class="newsticker-button newsticker-button--next" id="newsticker-button--next"
                        aria-label="previous article"><i class="ui-arrow-right"></i></button>
            </div>
        </div>
    </div>


</main>